version: '3.9'

services:
  postgres:
    # image: postgres
    container_name: u_postgres
    restart: always
    build: .
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
volumes:
  postgres:
